# version: '3.8'
#MongoDB 5.0+ requires a CPU with AVX support, => sử dụng image: mongo:4.4
services:
  db-mongo:
    image: mongo:6.0.6
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    expose:
      - 27017

  be-nest:
    build:
      context: .
      dockerfile: Dockerfile
    # restart: unless-stopped
    environment:
      - PORT=8080
      - NODE_ENV=production
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
      - MONGO_URL=mongodb+srv://lntt2018:PGte9qzGXeT58r2R@cluster0.d3jlrd7.mongodb.net/backendnestjs
=======
      - MONGO_URL=mongodb://root:123456@db-mongo:27017/hoidanit?authSource=admin
>>>>>>> 65cb50331c5ce6512690d86afe82ae81ad091fd6
=======
      - MONGO_URL=mongodb://root:123456@db-mongo:27017/hoidanit?authSource=admin
>>>>>>> parent of d4e9bd6 (Merge branch 'master' of https://github.com/tuannguyen20198/nestjs-basic)
=======
      - MONGO_URL=mongodb+srv://lntt2018:PGte9qzGXeT58r2R@cluster0.d3jlrd7.mongodb.net/backendnestjs
>>>>>>> parent of f40a6c3 (commit code)
      # - DB_HOST=host.docker.internal
    expose:
      - 8080
    ports:
      - 8080:8080

volumes:
  mongodb:

    # docker compose -p hoidanit-nest up -d
